# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a signed release AAB locally (does not upload to Play Store)"
  lane :build do
    # To run this lane: /opt/homebrew/Cellar/ruby/4.0.1/bin/bundle exec fastlane build
    gradle(task: "bundle", build_type: "Release")

    UI.success "✅ AAB generated at: #{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
  end

  desc "Build and upload to Google Play internal track"
  lane :deploy do
    # To run this lane: /opt/homebrew/Cellar/ruby/4.0.1/bin/bundle exec fastlane build
    gradle(task: "bundle", build_type: "Release")

    upload_to_play_store(
      track: "internal",
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    )
  end
end
